const data = {
    dashboard_id: '1955528198595706881',
    user_id: '1851503992350597122',
    name: 'Super',
    home: false,
    created_at: '1755069229170',
    widgets: [
        {
            widget_id: '1960632607480700930',
            data: {
                class: 'data_chart',
                type: 'pieChart',
                name: 'Pie',
                defaultRow: 4,
                defaultCol: 4,
                minRow: 2,
                minCol: 2,
                config: {
                    entity: {
                        value: '1950835401590567223',
                        label: 'DST Enable',
                        valueType: 'BOOLEAN',
                        description: 'PROPERTY, vs125-p, Time Info.',
                        rawData: {
                            deviceName: 'vs125-p',
                            integrationName: 'Milesight Development Platform',
                            entityId: '1950835401590567223',
                            entityAccessMod: 'R',
                            entityKey:
                                'msc-integration.device.68340204C51E0005.time_info.enable_dst',
                            entityType: 'PROPERTY',
                            entityName: 'DST Enable',
                            entityParentName: 'Time Info.',
                            entityValueAttribute: {
                                enum: {
                                    true: 'Enable',
                                    false: 'Disable',
                                },
                            },
                            entityValueType: 'BOOLEAN',
                            entityIsCustomized: false,
                            entityCreatedAt: 1753950379360,
                            entityUpdatedAt: 1753950379360,
                        },
                    },
                    title: 'Title 555',
                    time: 86400000,
                    metrics: 'COUNT',
                },
                pos: {
                    w: 3,
                    h: 3,
                    x: 0,
                    y: 1,
                    i: '1756286194837',
                    minW: 2,
                    maxW: 12,
                    minH: 2,
                    moved: false,
                    static: false,
                },
            },
        },
        {
            widget_id: '1959805985478115330',
            data: {
                class: 'data_chart',
                type: 'iconRemaining',
                name: 'Remaining',
                defaultRow: 1,
                defaultCol: 2,
                minRow: 1,
                minCol: 2,
                maxRow: 1,
                config: {
                    entity: {
                        value: '1920653175522988045',
                        label: 'Distance',
                        valueType: 'LONG',
                        description: 'PROPERTY, DEMO_EM500-UDL-C100',
                        rawData: {
                            deviceName: 'DEMO_EM500-UDL-C100',
                            integrationName: 'Milesight Development Platform',
                            entityId: '1920653175522988045',
                            entityAccessMod: 'R',
                            entityKey: 'msc-integration.device.DEMO_1920653046498713602.distance',
                            entityType: 'PROPERTY',
                            entityName: 'Distance',
                            entityValueAttribute: {
                                unit: 'mm',
                                min: 250,
                                max: 8000,
                            },
                            entityValueType: 'LONG',
                            entityIsCustomized: false,
                            entityCreatedAt: 1746754375759,
                            entityUpdatedAt: 1747033755938,
                        },
                    },
                    title: 'Title icon 666',
                    time: 31536000000,
                    metrics: 'AVG',
                    appearanceIcon: {
                        icon: 'AntPm10Icon',
                        color: '#5eafffff',
                    },
                },
                pos: {
                    w: 2,
                    h: 1,
                    x: 0,
                    y: 0,
                    i: '1959805985478115330',
                    minW: 2,
                    maxW: 12,
                    minH: 1,
                    maxH: 1,
                    moved: false,
                    static: false,
                },
            },
        },
        {
            widget_id: '1959806321844518913',
            data: {
                class: 'data_chart',
                type: 'lineChart',
                name: 'Line',
                defaultRow: 4,
                defaultCol: 4,
                minRow: 2,
                minCol: 2,
                config: {
                    title: 'Tem_Hum',
                    entityPosition: [
                        {
                            id: '1852267466534055948',
                            entity: {
                                value: '1852267466534055948',
                                label: 'Humidity',
                                valueType: 'DOUBLE',
                                description: 'PROPERTY',
                                rawData: {
                                    deviceName: 'AM308',
                                    integrationName: 'Milesight Development Platform',
                                    entityId: '1852267466534055948',
                                    entityAccessMod: 'R',
                                    entityKey:
                                        'msc-integration.device.DEMO_1852227367394222081.humidity',
                                    entityType: 'PROPERTY',
                                    entityName: 'Humidity',
                                    entityValueAttribute: {
                                        fractionDigits: 1,
                                        unit: '%RH',
                                        min: 0,
                                        max: 100,
                                    },
                                    entityValueType: 'DOUBLE',
                                    entityIsCustomized: false,
                                    entityCreatedAt: 1730449952161,
                                    entityUpdatedAt: 1730449952161,
                                },
                            },
                            position: 1,
                        },
                        {
                            id: '1852267466534055947',
                            entity: {
                                value: '1852267466534055947',
                                label: 'Temperature',
                                valueType: 'DOUBLE',
                                description: 'PROPERTY',
                                rawData: {
                                    deviceName: 'AM308',
                                    integrationName: 'Milesight Development Platform',
                                    entityId: '1852267466534055947',
                                    entityAccessMod: 'R',
                                    entityKey:
                                        'msc-integration.device.DEMO_1852227367394222081.temperature',
                                    entityType: 'PROPERTY',
                                    entityName: 'Temperature',
                                    entityValueAttribute: {
                                        fractionDigits: 1,
                                        unit: '°C',
                                        min: -20,
                                        max: 60,
                                    },
                                    entityValueType: 'DOUBLE',
                                    entityIsCustomized: false,
                                    entityCreatedAt: 1730449952160,
                                    entityUpdatedAt: 1730449952160,
                                },
                            },
                            position: 2,
                        },
                    ],
                    time: 31536000000,
                    leftYAxisUnit: 'Humidity(%RH) 666',
                    rightYAxisUnit: 'Temperature(°C) 999',
                },
                pos: {
                    w: 4,
                    h: 3,
                    x: 3,
                    y: 0,
                    i: '1959806321844518913',
                    minW: 2,
                    maxW: 9,
                    minH: 2,
                    moved: false,
                    static: false,
                },
            },
        },
    ],
    entity_ids: ['1920653175522988045', '1852267466534055948', '1852267466534055947'],
    entities: [
        {
            device_name: 'AM308',
            integration_name: 'Milesight Development Platform',
            entity_id: '1852267466534055947',
            entity_access_mod: 'R',
            entity_key: 'msc-integration.device.DEMO_1852227367394222081.temperature',
            entity_type: 'PROPERTY',
            entity_name: 'Temperature',
            entity_value_attribute: {
                fraction_digits: 1,
                unit: '°C',
                min: -20,
                max: 60,
            },
            entity_value_type: 'DOUBLE',
            entity_is_customized: false,
            entity_created_at: 1730449952160,
            entity_updated_at: 1730449952160,
        },
        {
            device_name: 'AM308',
            integration_name: 'Milesight Development Platform',
            entity_id: '1852267466534055948',
            entity_access_mod: 'R',
            entity_key: 'msc-integration.device.DEMO_1852227367394222081.humidity',
            entity_type: 'PROPERTY',
            entity_name: 'Humidity',
            entity_value_attribute: {
                fraction_digits: 1,
                unit: '%RH',
                min: 0,
                max: 100,
            },
            entity_value_type: 'DOUBLE',
            entity_is_customized: false,
            entity_created_at: 1730449952161,
            entity_updated_at: 1730449952161,
        },
        {
            device_name: 'DEMO_EM500-UDL-C100',
            integration_name: 'Milesight Development Platform',
            entity_id: '1920653175522988045',
            entity_access_mod: 'R',
            entity_key: 'msc-integration.device.DEMO_1920653046498713602.distance',
            entity_type: 'PROPERTY',
            entity_name: 'Distance',
            entity_value_attribute: {
                unit: 'mm',
                min: 250,
                max: 8000,
            },
            entity_value_type: 'LONG',
            entity_is_customized: false,
            entity_created_at: 1746754375759,
            entity_updated_at: 1747033755938,
        },
    ],
};

export default data;
