--liquibase formatted sql
--changeset alarm_rule:v1.4.0_20260128
CREATE TABLE IF NOT EXISTS t_alarm_rule (
    id                      BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               VARCHAR(255)  NOT NULL,
    name                    VARCHAR(512)  NOT NULL,
    device_ids              TEXT          NOT NULL,
    entity_key              VARCHAR(512)  NOT NULL,
    condition_op            VARCHAR(64)   NOT NULL,
    condition_value         VARCHAR(512),
    action_raise_alarm      BOOLEAN       NOT NULL DEFAULT TRUE,
    action_notify_email     BOOLEAN       NOT NULL DEFAULT FALSE,
    action_notify_webhook   BOOLEAN       NOT NULL DEFAULT FALSE,
    enabled                 BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at              BIGINT,
    updated_at              BIGINT
);
CREATE INDEX IF NOT EXISTS idx_alarm_rule_tenant ON t_alarm_rule (tenant_id);
