-- liquibase formatted sql
-- changeset alarm:v1.4.0_20260127
CREATE TABLE t_alarm (
    id             BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      VARCHAR(255) NOT NULL,
    device_id      BIGINT       NOT NULL,
    alarm_time     BIGINT       NOT NULL,
    alarm_content  VARCHAR(1024),
    alarm_status   BOOLEAN      NOT NULL DEFAULT TRUE,
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    address        VARCHAR(512),
    entity_key     VARCHAR(512),
    source         VARCHAR(64),
    created_at     BIGINT
);
CREATE INDEX idx_alarm_tenant_device ON t_alarm (tenant_id, device_id);
CREATE INDEX idx_alarm_tenant_time ON t_alarm (tenant_id, alarm_time);
CREATE INDEX idx_alarm_tenant_status ON t_alarm (tenant_id, alarm_status);
