# Beaver IoT Monolith + ChirpStack v4 (prebuilt image, JAR baked in)
#
# Use with zero-touch default: no JAR build, no integrations clone.
# Image: BEAVER_IMAGE (default ghcr.io/rifatsekerariot/beaver-iot:latest).
# ChirpStack JAR is inside the image; no volume mount.
# CHIRPSTACK_DEFAULT_TENANT_ID defaults to "default" so webhook accepts uplinks without X-Tenant-Id.

services:
  monolith:
    container_name: beaver-iot
    image: ${BEAVER_IMAGE:-ghcr.io/rifatsekerariot/beaver-iot:latest}
    restart: always
    ports:
      - "9080:80"
      - "1883:1883"
      - "8083:8083"
    environment:
      - "JAVA_OPTS=-Xmx1024m -Xms1024m"
      - "SPRING_OPTS=--spring.profiles.active=dev"
      - "DB_TYPE=h2"
      - "SPRING_DATASOURCE_URL=jdbc:h2:file:~/beaver-iot/h2/beaver;AUTO_SERVER=TRUE"
      - "SPRING_DATASOURCE_USERNAME=sa"
      - "SPRING_DATASOURCE_PASSWORD="
      - "SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver"
      - "CHIRPSTACK_DEFAULT_TENANT_ID=${CHIRPSTACK_DEFAULT_TENANT_ID:-default}"
