# Beaver IoT Monolith + ChirpStack v4 HTTP Integration
#
# 1. Build integrations (e.g. chirpstack-integration) and copy JARs to:
#      target/chirpstack/integrations/
# 2. Set CHIRPSTACK_DEFAULT_TENANT_ID to your Beaver tenant ID (or use X-Tenant-Id header).
# 3. In ChirpStack HTTP Integration, set event endpoint URL to:
#      http://<host>:8080/public/integration/chirpstack/webhook
#    (or :9080 if compose uses 9080:80; host = localhost or your server IP)
#
# Image: BEAVER_IMAGE (default ghcr.io/rifatsekerariot/beaver-iot:latest, widget’lı prebuilt).

services:
  monolith:
    container_name: beaver-iot
    image: ${BEAVER_IMAGE:-ghcr.io/rifatsekerariot/beaver-iot:latest}
    restart: always
    ports:
      - "9080:80"   # HTTP (Installation PDF: 80). Use 9080 if 8080 is busy.
      - "1883:1883" # MQTT (Installation PDF)
      - "8083:8083" # WebSocket (Docker Compose PDF)
    environment:
      - "JAVA_OPTS=-Xmx1024m -Xms1024m"
      - "SPRING_OPTS=--spring.profiles.active=dev"
      - "DB_TYPE=h2"
      - "SPRING_DATASOURCE_URL=jdbc:h2:file:~/beaver-iot/h2/beaver;AUTO_SERVER=TRUE"
      - "SPRING_DATASOURCE_USERNAME=sa"
      - "SPRING_DATASOURCE_PASSWORD="
      - "SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver"
      # ChirpStack webhook tenant when X-Tenant-Id header is not sent (set via env or deploy script)
      - "CHIRPSTACK_DEFAULT_TENANT_ID=${CHIRPSTACK_DEFAULT_TENANT_ID:-default}"
    volumes:
      - "./target/chirpstack/:/root/beaver-iot/"
