# platformariot: PostgreSQL + Beaver IoT (Alarm, widget'lar). Tek compose.
# Prebuilt: ghcr.io/rifatsekerariot/beaver-iot:latest (ChirpStack JAR dahil; webhook isteğe bağlı).
#
# Env (opsiyonel): BEAVER_IMAGE, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, CHIRPSTACK_DEFAULT_TENANT_ID

services:
  postgresql:
    container_name: beaver-iot-postgresql
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - beaver-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  monolith:
    container_name: beaver-iot
    image: ${BEAVER_IMAGE:-ghcr.io/rifatsekerariot/beaver-iot:latest}
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "9080:80"
      - "1883:1883"
      - "8083:8083"
    environment:
      - "JAVA_OPTS=-Xmx1024m -Xms1024m"
      - "SPRING_OPTS=--spring.profiles.active=dev"
      # Teşhis için: debug.ping.enabled=true ekle (örn. -Ddebug.ping.enabled=true)
      - "DB_TYPE=postgres"
      - "BLUEPRINT_LIBRARY_DEFAULT_ADDRESS_LOCAL_ZIP_FILE=/default_local_blueprint.zip"
      - "SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver"
      - "SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}"
      - "SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/${POSTGRES_DB:-postgres}"
      - "CHIRPSTACK_DEFAULT_TENANT_ID=${CHIRPSTACK_DEFAULT_TENANT_ID:-default}"
    volumes:
      - beaver-monolith-logs:/root/beaver-iot/logs

# Kalıcı volume'ler; deploy script down -v kullanmaz. Güncellemede veri korunur.
volumes:
  beaver-postgres-data:
  beaver-monolith-logs:
